name: deploy
run-name: Build & Deploy
on: [pull_request, push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm wrangler pages deploy build --project-name dval-in
